# Generated by Django 4.1.2 on 2022-10-28 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SnsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=50)),
                ("good", models.IntegerField()),
                ("read", models.IntegerField()),
                ("readText", models.TextField()),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
