# Generated by Django 4.1.2 on 2022-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snsmodel",
            name="good",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="snsmodel",
            name="read",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="snsmodel",
            name="readText",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
