# Generated by Django 4.1.2 on 2022-10-28 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snsmodel",
            name="posted_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
