# Generated by Django 4.1.2 on 2022-10-28 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0002_snsmodel_posted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snsmodel",
            name="posted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
